apiVersion: v1
kind: Service
metadata:
  namespace: {{ .Values.default }}
  name: {{ .Values.projectName }}
  annotations:
{{ toYaml .Values.annotations | indent 4 }}
  labels:
{{ toYaml .Values.annotations | indent 4 }}
spec:
  type: {{ .Values.service.type }}
  {{- if .Values.loadBalancerSourceRanges }}
  loadBalancerSourceRanges:
{{ toYaml .Values.loadBalancerSourceRanges | indent 4 }}
  {{- end }}
  selector:
    app: {{ .Values.projectName }}
  ports:
    - name: {{ .Values.projectName }}-port
      protocol: {{ .Values.service.protocol }}
      port: {{ .Values.service.port }}
      targetPort: {{ .Values.applicationPort }}
    - name: {{ .Values.projectName }}-metrics-port
      protocol: {{ .Values.service.protocol }}
      port: {{ .Values.prometheusPort }}
      targetPort: {{ .Values.prometheusPort }}